CONFIG_SERIAL=y
CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_ROM_START_OFFSET=0x0
CONFIG_WATCHDOG=y

CONFIG_MAIN_STACK_SIZE=8192
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096
CONFIG_REBOOT=y
CONFIG_POSIX_C_LIB_EXT=y
CONFIG_HEAP_MEM_POOL_SIZE=65536
CONFIG_THREAD_STACK_INFO=y
CONFIG_DYNAMIC_THREAD=y
CONFIG_DYNAMIC_THREAD_ALLOC=y

CONFIG_NETWORKING=y
CONFIG_HTTP_SERVER=y
CONFIG_NET_TCP=y
CONFIG_NET_SOCKETS=y
CONFIG_EVENTFD=y
CONFIG_ZVFS_EVENTFD_MAX=4
CONFIG_ZVFS_POLL_MAX=32
CONFIG_NET_MAX_CONTEXTS=16
CONFIG_NET_MAX_CONN=16
CONFIG_WIFI=y
CONFIG_NET_CONNECTION_MANAGER=y
CONFIG_NET_L2_WIFI_MGMT=y
CONFIG_NET_L2_ETHERNET=y
CONFIG_NET_IPV4=y
CONFIG_NET_DHCPV4=y
CONFIG_NET_DHCPV4_SERVER=y
CONFIG_NET_MGMT_EVENT=y
CONFIG_NET_LOG=y
CONFIG_LOG_BACKEND_NET=y
# CONFIG_LOG_BACKEND_NET_AUTOSTART=y
CONFIG_NET_HOSTNAME_ENABLE=y
# CONFIG_LOG_BACKEND_NET_USE_CONNECTION_MANAGER=y
CONFIG_LOG_PROCESS_THREAD_STACK_SIZE=4096
CONFIG_NET_TCP_WORKQ_STACK_SIZE=4096
CONFIG_NET_RX_STACK_SIZE=4096
CONFIG_NET_TX_STACK_SIZE=4096

# IPv6 Configuration
CONFIG_NET_IPV6=y
CONFIG_NET_IPV6_ND=y
CONFIG_NET_IPV6_DAD=y
CONFIG_NET_IPV6_MLD=y
CONFIG_NET_IPV6_RA_RDNSS=y
CONFIG_NET_DHCPV6=y
CONFIG_DNS_RESOLVER=y
# Console
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_NET_SOCKETS_SERVICE_STACK_SIZE=4096

# NVS Storage
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_NVS=y
CONFIG_NET_MGMT_EVENT_INFO=y
CONFIG_NET_MGMT_EVENT_STACK_SIZE=4096
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_MQTT_LIB=y
CONFIG_SYS_HEAP_RUNTIME_STATS=y
CONFIG_EVENTS=y

CONFIG_NET_IF_UNICAST_IPV4_ADDR_COUNT=3
CONFIG_BOOTLOADER_MCUBOOT=y
CONFIG_MCUBOOT_IMG_MANAGER=y
CONFIG_IMG_MANAGER=y
CONFIG_STREAM_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_MCUBOOT_BOOTUTIL_LIB=y
CONFIG_HTTP_CLIENT=y
CONFIG_MCUBOOT_SIGNATURE_KEY_FILE="mcuboot/root-rsa-2048.pem"
CONFIG_MCUBOOT_GENERATE_CONFIRMED_IMAGE=y
CONFIG_FLASH_LOAD_OFFSET=0x0
CONFIG_FLASH_LOAD_SIZE=0x170000
CONFIG_USE_DT_CODE_PARTITION=n
CONFIG_MCUBOOT_EXTRA_IMGTOOL_ARGS="--version 7.0.0"
CONFIG_MCUBOOT_IMGTOOL_SIGN_VERSION="7.0.0+0"
CONFIG_IMG_ERASE_PROGRESSIVELY=y

CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_CHIP=y
CONFIG_CHIP_PROJECT_CONFIG="src/matter/CHIPProjectConfig.h"
CONFIG_CHIP_LIB_SHELL=n
CONFIG_CHIP_BUILD_TESTS=n

CONFIG_CHIP_OTA_REQUESTOR=y
CONFIG_CHIP_EXTENDED_DISCOVERY=y
CONFIG_INIT_STACKS=y
CONFIG_THREAD_STACK_INFO=y
CONFIG_TEST_RANDOM_GENERATOR=y
