/* Hand-written IMClusterCommandHandler.cpp for Sesame.
 *
 * Normally generated by ZAP from im-cluster-command-handler.zapt.  We
 * maintain it by hand because we don't run ZAP in the build.
 *
 * Only clusters that use the old ember-callback dispatch model need entries
 * here.  Clusters that implement CommandHandlerInterface (General/Administrator
 * Commissioning, Network Commissioning) self-register and handle commands
 * via InvokeCommand() — no entry needed.
 */

#include <app-common/zap-generated/callback.h>
#include <app-common/zap-generated/cluster-objects.h>
#include <app-common/zap-generated/ids/Clusters.h>
#include <app-common/zap-generated/ids/Commands.h>
#include <app/CommandHandler.h>
#include <app/InteractionModelEngine.h>
#include <app/util/util.h>
#include <lib/core/CHIPSafeCasts.h>
#include <lib/support/TypeTraits.h>
#include <protocols/interaction_model/StatusCode.h>

namespace chip {
namespace app {

namespace Clusters {

/* -------- Window Covering (0x0102) -------- */
namespace WindowCovering {

static Protocols::InteractionModel::Status DispatchServerCommand(CommandHandler * apCommandObj,
                                                                 const ConcreteCommandPath & aCommandPath,
                                                                 TLV::TLVReader & aDataTlv)
{
    CHIP_ERROR tlvError = CHIP_NO_ERROR;
    bool wasHandled     = false;

    switch (aCommandPath.mCommandId)
    {
    case Commands::UpOrOpen::Id: {
        Commands::UpOrOpen::DecodableType commandData;
        tlvError  = DataModel::Decode(aDataTlv, commandData);
        wasHandled = tlvError == CHIP_NO_ERROR &&
            emberAfWindowCoveringClusterUpOrOpenCallback(apCommandObj, aCommandPath, commandData);
        break;
    }
    case Commands::DownOrClose::Id: {
        Commands::DownOrClose::DecodableType commandData;
        tlvError  = DataModel::Decode(aDataTlv, commandData);
        wasHandled = tlvError == CHIP_NO_ERROR &&
            emberAfWindowCoveringClusterDownOrCloseCallback(apCommandObj, aCommandPath, commandData);
        break;
    }
    case Commands::StopMotion::Id: {
        Commands::StopMotion::DecodableType commandData;
        tlvError  = DataModel::Decode(aDataTlv, commandData);
        wasHandled = tlvError == CHIP_NO_ERROR &&
            emberAfWindowCoveringClusterStopMotionCallback(apCommandObj, aCommandPath, commandData);
        break;
    }
    case Commands::GoToLiftValue::Id: {
        Commands::GoToLiftValue::DecodableType commandData;
        tlvError  = DataModel::Decode(aDataTlv, commandData);
        wasHandled = tlvError == CHIP_NO_ERROR &&
            emberAfWindowCoveringClusterGoToLiftValueCallback(apCommandObj, aCommandPath, commandData);
        break;
    }
    case Commands::GoToLiftPercentage::Id: {
        Commands::GoToLiftPercentage::DecodableType commandData;
        tlvError  = DataModel::Decode(aDataTlv, commandData);
        wasHandled = tlvError == CHIP_NO_ERROR &&
            emberAfWindowCoveringClusterGoToLiftPercentageCallback(apCommandObj, aCommandPath, commandData);
        break;
    }
    case Commands::GoToTiltValue::Id: {
        Commands::GoToTiltValue::DecodableType commandData;
        tlvError  = DataModel::Decode(aDataTlv, commandData);
        wasHandled = tlvError == CHIP_NO_ERROR &&
            emberAfWindowCoveringClusterGoToTiltValueCallback(apCommandObj, aCommandPath, commandData);
        break;
    }
    case Commands::GoToTiltPercentage::Id: {
        Commands::GoToTiltPercentage::DecodableType commandData;
        tlvError  = DataModel::Decode(aDataTlv, commandData);
        wasHandled = tlvError == CHIP_NO_ERROR &&
            emberAfWindowCoveringClusterGoToTiltPercentageCallback(apCommandObj, aCommandPath, commandData);
        break;
    }
    default:
        ChipLogError(Zcl, "Unknown WindowCovering command " ChipLogFormatMEI, ChipLogValueMEI(aCommandPath.mCommandId));
        return Protocols::InteractionModel::Status::UnsupportedCommand;
    }

    if (tlvError != CHIP_NO_ERROR || !wasHandled)
        return Protocols::InteractionModel::Status::InvalidCommand;

    return Protocols::InteractionModel::Status::Success;
}

} // namespace WindowCovering

/* -------- Operational Credentials (0x003E) -------- */
namespace OperationalCredentials {

static Protocols::InteractionModel::Status DispatchServerCommand(CommandHandler * apCommandObj,
                                                                 const ConcreteCommandPath & aCommandPath,
                                                                 TLV::TLVReader & aDataTlv)
{
    CHIP_ERROR tlvError = CHIP_NO_ERROR;
    bool wasHandled     = false;

    switch (aCommandPath.mCommandId)
    {
    case Commands::AttestationRequest::Id: {
        Commands::AttestationRequest::DecodableType commandData;
        tlvError  = DataModel::Decode(aDataTlv, commandData);
        wasHandled = tlvError == CHIP_NO_ERROR &&
            emberAfOperationalCredentialsClusterAttestationRequestCallback(apCommandObj, aCommandPath, commandData);
        break;
    }
    case Commands::CertificateChainRequest::Id: {
        Commands::CertificateChainRequest::DecodableType commandData;
        tlvError  = DataModel::Decode(aDataTlv, commandData);
        wasHandled = tlvError == CHIP_NO_ERROR &&
            emberAfOperationalCredentialsClusterCertificateChainRequestCallback(apCommandObj, aCommandPath, commandData);
        break;
    }
    case Commands::CSRRequest::Id: {
        Commands::CSRRequest::DecodableType commandData;
        tlvError  = DataModel::Decode(aDataTlv, commandData);
        wasHandled = tlvError == CHIP_NO_ERROR &&
            emberAfOperationalCredentialsClusterCSRRequestCallback(apCommandObj, aCommandPath, commandData);
        break;
    }
    case Commands::AddNOC::Id: {
        Commands::AddNOC::DecodableType commandData;
        tlvError  = DataModel::Decode(aDataTlv, commandData);
        wasHandled = tlvError == CHIP_NO_ERROR &&
            emberAfOperationalCredentialsClusterAddNOCCallback(apCommandObj, aCommandPath, commandData);
        break;
    }
    case Commands::UpdateNOC::Id: {
        Commands::UpdateNOC::DecodableType commandData;
        tlvError  = commandData.Decode(aDataTlv, apCommandObj->GetAccessingFabricIndex());
        wasHandled = tlvError == CHIP_NO_ERROR &&
            emberAfOperationalCredentialsClusterUpdateNOCCallback(apCommandObj, aCommandPath, commandData);
        break;
    }
    case Commands::UpdateFabricLabel::Id: {
        Commands::UpdateFabricLabel::DecodableType commandData;
        tlvError  = commandData.Decode(aDataTlv, apCommandObj->GetAccessingFabricIndex());
        wasHandled = tlvError == CHIP_NO_ERROR &&
            emberAfOperationalCredentialsClusterUpdateFabricLabelCallback(apCommandObj, aCommandPath, commandData);
        break;
    }
    case Commands::RemoveFabric::Id: {
        Commands::RemoveFabric::DecodableType commandData;
        tlvError  = DataModel::Decode(aDataTlv, commandData);
        wasHandled = tlvError == CHIP_NO_ERROR &&
            emberAfOperationalCredentialsClusterRemoveFabricCallback(apCommandObj, aCommandPath, commandData);
        break;
    }
    case Commands::AddTrustedRootCertificate::Id: {
        Commands::AddTrustedRootCertificate::DecodableType commandData;
        tlvError  = DataModel::Decode(aDataTlv, commandData);
        wasHandled = tlvError == CHIP_NO_ERROR &&
            emberAfOperationalCredentialsClusterAddTrustedRootCertificateCallback(apCommandObj, aCommandPath, commandData);
        break;
    }
    case Commands::SetVIDVerificationStatement::Id: {
        Commands::SetVIDVerificationStatement::DecodableType commandData;
        tlvError  = commandData.Decode(aDataTlv, apCommandObj->GetAccessingFabricIndex());
        wasHandled = tlvError == CHIP_NO_ERROR &&
            emberAfOperationalCredentialsClusterSetVIDVerificationStatementCallback(apCommandObj, aCommandPath, commandData);
        break;
    }
    case Commands::SignVIDVerificationRequest::Id: {
        Commands::SignVIDVerificationRequest::DecodableType commandData;
        tlvError  = DataModel::Decode(aDataTlv, commandData);
        wasHandled = tlvError == CHIP_NO_ERROR &&
            emberAfOperationalCredentialsClusterSignVIDVerificationRequestCallback(apCommandObj, aCommandPath, commandData);
        break;
    }
    default:
        ChipLogError(Zcl, "Unknown OperationalCredentials command " ChipLogFormatMEI, ChipLogValueMEI(aCommandPath.mCommandId));
        return Protocols::InteractionModel::Status::UnsupportedCommand;
    }

    if (tlvError != CHIP_NO_ERROR || !wasHandled)
        return Protocols::InteractionModel::Status::InvalidCommand;

    return Protocols::InteractionModel::Status::Success;
}

} // namespace OperationalCredentials

/* -------- Access Control (0x001F) -------- */
namespace AccessControl {

static Protocols::InteractionModel::Status DispatchServerCommand(CommandHandler * apCommandObj,
                                                                 const ConcreteCommandPath & aCommandPath,
                                                                 TLV::TLVReader & aDataTlv)
{
    CHIP_ERROR tlvError = CHIP_NO_ERROR;
    bool wasHandled     = false;

    switch (aCommandPath.mCommandId)
    {
    default:
        return Protocols::InteractionModel::Status::UnsupportedCommand;
    }

    if (tlvError != CHIP_NO_ERROR || !wasHandled)
        return Protocols::InteractionModel::Status::InvalidCommand;

    return Protocols::InteractionModel::Status::Success;
}

} // namespace AccessControl

/* -------- Group Key Management (0x003F) -------- */
namespace GroupKeyManagement {

static Protocols::InteractionModel::Status DispatchServerCommand(CommandHandler * apCommandObj,
                                                                 const ConcreteCommandPath & aCommandPath,
                                                                 TLV::TLVReader & aDataTlv)
{
    CHIP_ERROR tlvError = CHIP_NO_ERROR;
    bool wasHandled     = false;

    switch (aCommandPath.mCommandId)
    {
    case Commands::KeySetWrite::Id: {
        Commands::KeySetWrite::DecodableType commandData;
        tlvError  = commandData.Decode(aDataTlv, apCommandObj->GetAccessingFabricIndex());
        wasHandled = tlvError == CHIP_NO_ERROR &&
            emberAfGroupKeyManagementClusterKeySetWriteCallback(apCommandObj, aCommandPath, commandData);
        break;
    }
    case Commands::KeySetRead::Id: {
        Commands::KeySetRead::DecodableType commandData;
        tlvError  = commandData.Decode(aDataTlv, apCommandObj->GetAccessingFabricIndex());
        wasHandled = tlvError == CHIP_NO_ERROR &&
            emberAfGroupKeyManagementClusterKeySetReadCallback(apCommandObj, aCommandPath, commandData);
        break;
    }
    case Commands::KeySetRemove::Id: {
        Commands::KeySetRemove::DecodableType commandData;
        tlvError  = commandData.Decode(aDataTlv, apCommandObj->GetAccessingFabricIndex());
        wasHandled = tlvError == CHIP_NO_ERROR &&
            emberAfGroupKeyManagementClusterKeySetRemoveCallback(apCommandObj, aCommandPath, commandData);
        break;
    }
    case Commands::KeySetReadAllIndices::Id: {
        Commands::KeySetReadAllIndices::DecodableType commandData;
        tlvError  = commandData.Decode(aDataTlv, apCommandObj->GetAccessingFabricIndex());
        wasHandled = tlvError == CHIP_NO_ERROR &&
            emberAfGroupKeyManagementClusterKeySetReadAllIndicesCallback(apCommandObj, aCommandPath, commandData);
        break;
    }
    default:
        return Protocols::InteractionModel::Status::UnsupportedCommand;
    }

    if (tlvError != CHIP_NO_ERROR || !wasHandled)
        return Protocols::InteractionModel::Status::InvalidCommand;

    return Protocols::InteractionModel::Status::Success;
}

} // namespace GroupKeyManagement

/* -------- OTA Software Update Requestor (0x002A) -------- */
namespace OtaSoftwareUpdateRequestor {

static Protocols::InteractionModel::Status DispatchServerCommand(CommandHandler * apCommandObj,
                                                                 const ConcreteCommandPath & aCommandPath,
                                                                 TLV::TLVReader & aDataTlv)
{
    CHIP_ERROR tlvError = CHIP_NO_ERROR;
    bool wasHandled     = false;

    switch (aCommandPath.mCommandId)
    {
    case Commands::AnnounceOTAProvider::Id: {
        Commands::AnnounceOTAProvider::DecodableType commandData;
        tlvError  = DataModel::Decode(aDataTlv, commandData);
        wasHandled = tlvError == CHIP_NO_ERROR &&
            emberAfOtaSoftwareUpdateRequestorClusterAnnounceOTAProviderCallback(apCommandObj, aCommandPath, commandData);
        break;
    }
    default:
        return Protocols::InteractionModel::Status::UnsupportedCommand;
    }

    if (tlvError != CHIP_NO_ERROR || !wasHandled)
        return Protocols::InteractionModel::Status::InvalidCommand;

    return Protocols::InteractionModel::Status::Success;
}

} // namespace OtaSoftwareUpdateRequestor

} // namespace Clusters

void DispatchSingleClusterCommand(const ConcreteCommandPath & aCommandPath, TLV::TLVReader & aReader,
                                  CommandHandler * apCommandObj)
{
    Protocols::InteractionModel::Status errorStatus = Protocols::InteractionModel::Status::Success;

    switch (aCommandPath.mClusterId)
    {
    case Clusters::WindowCovering::Id:
        errorStatus = Clusters::WindowCovering::DispatchServerCommand(apCommandObj, aCommandPath, aReader);
        break;
    case Clusters::OperationalCredentials::Id:
        errorStatus = Clusters::OperationalCredentials::DispatchServerCommand(apCommandObj, aCommandPath, aReader);
        break;
    case Clusters::AccessControl::Id:
        errorStatus = Clusters::AccessControl::DispatchServerCommand(apCommandObj, aCommandPath, aReader);
        break;
    case Clusters::GroupKeyManagement::Id:
        errorStatus = Clusters::GroupKeyManagement::DispatchServerCommand(apCommandObj, aCommandPath, aReader);
        break;
    case Clusters::OtaSoftwareUpdateRequestor::Id:
        errorStatus = Clusters::OtaSoftwareUpdateRequestor::DispatchServerCommand(apCommandObj, aCommandPath, aReader);
        break;
    default:
        ChipLogError(Zcl, "Unknown cluster " ChipLogFormatMEI, ChipLogValueMEI(aCommandPath.mClusterId));
        errorStatus = Protocols::InteractionModel::Status::UnsupportedCluster;
        break;
    }

    if (errorStatus != Protocols::InteractionModel::Status::Success)
    {
        apCommandObj->AddStatus(aCommandPath, errorStatus);
    }
}

} // namespace app
} // namespace chip
