/*
 * Sesame-specific overrides for CHIP compile-time configuration.
 * Picked up via CHIP_PROJECT_CONFIG_INCLUDE = <CHIPProjectConfig.h>.
 */
#pragma once

#define CHIP_DEVICE_CONFIG_DEVICE_VENDOR_ID 0xFFF1
#define CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_ID 0x8004
#define CHIP_DEVICE_CONFIG_DEVICE_VENDOR_NAME "Sesame"
#define CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_NAME "Sesame Garage Door"
#define CHIP_DEVICE_CONFIG_DEVICE_HARDWARE_VERSION 1
#define CHIP_DEVICE_CONFIG_DEVICE_HARDWARE_VERSION_STRING "v1"

#define CHIP_CONFIG_MAX_FABRICS 5

#define CHIP_DEVICE_CONFIG_ENABLE_CHIPOBLE 0
#define CONFIG_NETWORK_LAYER_BLE 0

#define CHIP_DEVICE_CONFIG_USE_TEST_SERIAL_NUMBER "SESAME-DEV"
