# Reads each .be input and emits a C header with one `static const char` per
# file holding the source text (test/asserts at the bottom of the .be file are
# stripped — the convention is that everything after a `#-` line is sample
# code we shouldn't ship).
#
# Inputs: -DOUT=<output.h> -DINPUTS=<;-separated absolute .be paths>

set(_out "")
string(APPEND _out "/* generated by embed_be.cmake — do not edit */\n")
string(APPEND _out "#pragma once\n\n")

foreach(input IN LISTS INPUTS)
    get_filename_component(stem "${input}" NAME_WE)
    file(READ "${input}" content)
    # Strip everything from the first `#-` block-comment opener onward.
    string(REGEX REPLACE "\n#-.*" "\n" content "${content}")
    # Escape for C string literal.
    string(REPLACE "\\" "\\\\" content "${content}")
    string(REPLACE "\"" "\\\"" content "${content}")
    string(REPLACE "\n" "\\n\"\n  \"" content "${content}")
    string(APPEND _out "static const char embedded_be_${stem}[] =\n")
    string(APPEND _out "  \"${content}\";\n\n")
endforeach()

file(WRITE "${OUT}" "${_out}")
