# Disable MW320 hardware
CONFIG_WIFI_MW320=n

# Enable TAP Ethernet
CONFIG_NET_L2_ETHERNET=y
CONFIG_ETH_NATIVE_TAP=y

# Ethernet requires MAC address


# Disable sysbuild mcuboot requirements
CONFIG_BOOTLOADER_MCUBOOT=n
CONFIG_BUILD_OUTPUT_BIN=n
CONFIG_UART_CONSOLE=n
CONFIG_POSIX_ARCH_CONSOLE=y
CONFIG_LOG_BACKEND_UART=n
CONFIG_LOG_BACKEND_NATIVE_POSIX=y
CONFIG_LOG_MODE_IMMEDIATE=y
