# Disable MW320 hardware
CONFIG_WIFI_MW320=n

# Enable TAP Ethernet
CONFIG_NET_L2_ETHERNET=y
CONFIG_ETH_NATIVE_POSIX=y
CONFIG_NATIVE_SIM_ETH_DRV=y

# Ethernet requires MAC address
CONFIG_ETH_NATIVE_POSIX_RANDOM_MAC=y

# Set network interface to tap (zeth0)
CONFIG_ETH_NATIVE_POSIX_SETUP_SCRIPT=""
CONFIG_ETH_NATIVE_POSIX_DRV_NAME="zeth"

# Disable sysbuild mcuboot requirements
CONFIG_BOOTLOADER_MCUBOOT=n
