// Generated by write_buildconfig_header.py
// From "//third_party/connectedhomeip/src/inet:gen_inet_buildconfig"

#ifndef INET_INETBUILDCONFIG_H_
#define INET_INETBUILDCONFIG_H_

#define INET_CONFIG_TEST 0
#ifdef USE_QEMU
#define INET_CONFIG_ENABLE_IPV4 0
#else
#define INET_CONFIG_ENABLE_IPV4 1
#endif
#define INET_CONFIG_ENABLE_TCP_ENDPOINT 1
#define INET_CONFIG_ENABLE_UDP_ENDPOINT 1
#define INET_PROJECT_CONFIG_INCLUDE <CHIPProjectConfig.h>
#define INET_PLATFORM_CONFIG_INCLUDE <platform/nxp/mw320/InetPlatformConfig.h>
#define INET_TCP_END_POINT_IMPL_CONFIG_FILE <inet/TCPEndPointImplSockets.h>
#define INET_UDP_END_POINT_IMPL_CONFIG_FILE <inet/UDPEndPointImplSockets.h>

#endif  // INET_INETBUILDCONFIG_H_
