/* Auto-generated from src/logs_page.html - DO NOT EDIT MANUALLY */
#pragma once

static const char logs_html[] =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"utf-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
"<title>Sesame Logs</title>\n"
"<style>\n"
"  :root {\n"
"    --bg: #121212;\n"
"    --toolbar-bg: #1e1e1e;\n"
"    --border: #333333;\n"
"    --text: #cccccc;\n"
"    --text-dim: #888888;\n"
"    --badge-live-bg: #0f391e;\n"
"    --badge-live-fg: #4ade80;\n"
"    --badge-disc-bg: #451a1a;\n"
"    --badge-disc-fg: #f87171;\n"
"    --badge-wait-bg: #422006;\n"
"    --badge-wait-fg: #facc15;\n"
"    --btn-bg: #2d2d2d;\n"
"    --btn-hover: #3d3d3d;\n"
"    --log-bg: #181818;\n"
"  }\n"
"  * { box-sizing: border-box; margin: 0; padding: 0; }\n"
"  body {\n"
"    background: var(--bg);\n"
"    color: var(--text);\n"
"    font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif;\n"
"    height: 100vh;\n"
"    display: flex;\n"
"    flex-direction: column;\n"
"    overflow: hidden;\n"
"  }\n"
"  header {\n"
"    background: var(--toolbar-bg);\n"
"    border-bottom: 1px solid var(--border);\n"
"    padding: 10px 16px;\n"
"    display: flex;\n"
"    flex-wrap: wrap;\n"
"    align-items: center;\n"
"    justify-content: space-between;\n"
"    gap: 10px;\n"
"  }\n"
"  .title-group {\n"
"    display: flex;\n"
"    align-items: center;\n"
"    gap: 12px;\n"
"  }\n"
"  h1 { font-size: 16px; font-weight: 600; color: #fff; }\n"
"  .badge {\n"
"    font-size: 11px;\n"
"    font-weight: 600;\n"
"    padding: 3px 8px;\n"
"    border-radius: 9999px;\n"
"    display: inline-flex;\n"
"    align-items: center;\n"
"    gap: 5px;\n"
"  }\n"
"  .badge-live { background: var(--badge-live-bg); color: var(--badge-live-fg); }\n"
"  .badge-disc { background: var(--badge-disc-bg); color: var(--badge-disc-fg); }\n"
"  .badge-wait { background: var(--badge-wait-bg); color: var(--badge-wait-fg); }\n"
"  .dot { width: 6px; height: 6px; border-radius: 50%; background: currentColor; }\n"
"  .toolbar {\n"
"    display: flex;\n"
"    align-items: center;\n"
"    flex-wrap: wrap;\n"
"    gap: 8px;\n"
"  }\n"
"  input[type=\"text\"] {\n"
"    background: #252525;\n"
"    border: 1px solid var(--border);\n"
"    color: #fff;\n"
"    padding: 5px 10px;\n"
"    border-radius: 4px;\n"
"    font-size: 13px;\n"
"    outline: none;\n"
"    width: 160px;\n"
"  }\n"
"  input[type=\"text\"]:focus { border-color: #3b82f6; }\n"
"  button, .link-btn {\n"
"    background: var(--btn-bg);\n"
"    color: #eee;\n"
"    border: 1px solid var(--border);\n"
"    padding: 5px 10px;\n"
"    border-radius: 4px;\n"
"    font-size: 12px;\n"
"    font-weight: 500;\n"
"    cursor: pointer;\n"
"    text-decoration: none;\n"
"    display: inline-flex;\n"
"    align-items: center;\n"
"    gap: 4px;\n"
"  }\n"
"  button:hover, .link-btn:hover { background: var(--btn-hover); color: #fff; }\n"
"  .toggle-label {\n"
"    font-size: 12px;\n"
"    color: var(--text-dim);\n"
"    display: inline-flex;\n"
"    align-items: center;\n"
"    gap: 4px;\n"
"    cursor: pointer;\n"
"    user-select: none;\n"
"  }\n"
"  #log-container {\n"
"    flex: 1;\n"
"    overflow-y: auto;\n"
"    background: var(--log-bg);\n"
"    padding: 12px 16px;\n"
"    font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;\n"
"    font-size: 12px;\n"
"    line-height: 1.5;\n"
"    white-space: pre-wrap;\n"
"    word-break: break-all;\n"
"  }\n"
"  .log-line { display: block; }\n"
"  .log-err { color: #f87171; }\n"
"  .log-wrn { color: #fbbf24; }\n"
"  .log-inf { color: #60a5fa; }\n"
"  .log-dbg { color: #9ca3af; }\n"
"  footer {\n"
"    background: var(--toolbar-bg);\n"
"    border-top: 1px solid var(--border);\n"
"    padding: 4px 16px;\n"
"    font-size: 11px;\n"
"    color: var(--text-dim);\n"
"    display: flex;\n"
"    justify-content: space-between;\n"
"  }\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<header>\n"
"  <div class=\"title-group\">\n"
"    <h1>Sesame Logs</h1>\n"
"    <span id=\"status-badge\" class=\"badge badge-wait\"><span class=\"dot\"></span>Connecting...</span>\n"
"  </div>\n"
"  <div class=\"toolbar\">\n"
"    <input type=\"text\" id=\"filter-input\" placeholder=\"Filter logs...\">\n"
"    <label class=\"toggle-label\"><input type=\"checkbox\" id=\"autoscroll-chk\" checked> Auto-scroll</label>\n"
"    <button id=\"pause-btn\">Pause</button>\n"
"    <button id=\"clear-btn\">Clear</button>\n"
"    <button id=\"download-btn\">Download</button>\n"
"    <a href=\"/matter\" class=\"link-btn\">Matter Setup</a>\n"
"  </div>\n"
"</header>\n"
"<div id=\"log-container\"></div>\n"
"<footer>\n"
"  <span id=\"line-count\">0 lines</span>\n"
"  <span id=\"port-info\">WS: :8080/ws/logs | HTTP: /logs</span>\n"
"</footer>\n"
"<script>\n"
"(function() {\n"
"  const container = document.getElementById('log-container');\n"
"  const statusBadge = document.getElementById('status-badge');\n"
"  const filterInput = document.getElementById('filter-input');\n"
"  const autoscrollChk = document.getElementById('autoscroll-chk');\n"
"  const pauseBtn = document.getElementById('pause-btn');\n"
"  const clearBtn = document.getElementById('clear-btn');\n"
"  const downloadBtn = document.getElementById('download-btn');\n"
"  const lineCountSpan = document.getElementById('line-count');\n"
"\n"
"  let allLines = [];\n"
"  let isPaused = false;\n"
"  let totalLineCount = 0;\n"
"  let ws = null;\n"
"  let reconnectTimer = null;\n"
"\n"
"  function setStatus(type, text) {\n"
"    statusBadge.className = 'badge badge-' + type;\n"
"    statusBadge.innerHTML = '<span class=\"dot\"></span>' + text;\n"
"  }\n"
"\n"
"  function renderLine(text) {\n"
"    const div = document.createElement('span');\n"
"    div.className = 'log-line';\n"
"    if (text.includes('[ERR]') || text.includes('<err>')) div.classList.add('log-err');\n"
"    else if (text.includes('[WRN]') || text.includes('<wrn>')) div.classList.add('log-wrn');\n"
"    else if (text.includes('[INF]') || text.includes('<inf>')) div.classList.add('log-inf');\n"
"    else if (text.includes('[DBG]') || text.includes('<dbg>')) div.classList.add('log-dbg');\n"
"    div.textContent = text;\n"
"    return div;\n"
"  }\n"
"\n"
"  function appendChunk(chunk) {\n"
"    const lines = chunk.split('\\n');\n"
"    const filter = filterInput.value.toLowerCase();\n"
"    const shouldScroll = autoscrollChk.checked;\n"
"\n"
"    for (let i = 0; i < lines.length; i++) {\n"
"      const line = lines[i];\n"
"      if (!line && i === lines.length - 1) continue;\n"
"      allLines.push(line);\n"
"      totalLineCount++;\n"
"      if (!isPaused) {\n"
"        if (!filter || line.toLowerCase().includes(filter)) {\n"
"          container.appendChild(renderLine(line + '\\n'));\n"
"        }\n"
"      }\n"
"    }\n"
"\n"
"    lineCountSpan.textContent = totalLineCount + ' lines';\n"
"\n"
"    if (shouldScroll && !isPaused) {\n"
"      container.scrollTop = container.scrollHeight;\n"
"    }\n"
"  }\n"
"\n"
"  function refilter() {\n"
"    container.innerHTML = '';\n"
"    const filter = filterInput.value.toLowerCase();\n"
"    for (let i = 0; i < allLines.length; i++) {\n"
"      const line = allLines[i];\n"
"      if (!filter || line.toLowerCase().includes(filter)) {\n"
"        container.appendChild(renderLine(line + '\\n'));\n"
"      }\n"
"    }\n"
"    if (autoscrollChk.checked) {\n"
"      container.scrollTop = container.scrollHeight;\n"
"    }\n"
"  }\n"
"\n"
"  filterInput.addEventListener('input', refilter);\n"
"\n"
"  clearBtn.addEventListener('click', function() {\n"
"    allLines = [];\n"
"    totalLineCount = 0;\n"
"    container.innerHTML = '';\n"
"    lineCountSpan.textContent = '0 lines';\n"
"  });\n"
"\n"
"  pauseBtn.addEventListener('click', function() {\n"
"    isPaused = !isPaused;\n"
"    pauseBtn.textContent = isPaused ? 'Resume' : 'Pause';\n"
"    if (!isPaused) refilter();\n"
"  });\n"
"\n"
"  downloadBtn.addEventListener('click', function() {\n"
"    const blob = new Blob([allLines.join('\\n')], { type: 'text/plain' });\n"
"    const url = URL.createObjectURL(blob);\n"
"    const a = document.createElement('a');\n"
"    a.href = url;\n"
"    a.download = 'sesame.log';\n"
"    a.click();\n"
"    URL.revokeObjectURL(url);\n"
"  });\n"
"\n"
"  function connectWs() {\n"
"    if (reconnectTimer) clearTimeout(reconnectTimer);\n"
"    const wsUrl = (location.protocol === 'https:' ? 'wss://' : 'ws://') + location.host + '/ws/logs';\n"
"    try {\n"
"      ws = new WebSocket(wsUrl);\n"
"    } catch(e) {\n"
"      fallbackHttp();\n"
"      return;\n"
"    }\n"
"\n"
"    ws.onopen = function() {\n"
"      setStatus('live', 'Live');\n"
"    };\n"
"\n"
"    ws.onmessage = function(evt) {\n"
"      if (typeof evt.data === 'string') {\n"
"        appendChunk(evt.data);\n"
"      }\n"
"    };\n"
"\n"
"    ws.onclose = function() {\n"
"      setStatus('disc', 'Disconnected');\n"
"      reconnectTimer = setTimeout(connectWs, 2000);\n"
"    };\n"
"\n"
"    ws.onerror = function() {\n"
"      setStatus('disc', 'Error');\n"
"      ws.close();\n"
"    };\n"
"  }\n"
"\n"
"  function fallbackHttp() {\n"
"    fetch('/logs')\n"
"      .then(function(res) { return res.text(); })\n"
"      .then(function(data) {\n"
"        appendChunk(data);\n"
"        setStatus('disc', 'Snapshot');\n"
"      })\n"
"      .catch(function(err) {\n"
"        setStatus('disc', 'Error');\n"
"      });\n"
"  }\n"
"\n"
"  connectWs();\n"
"})();\n"
"</script>\n"
"</body>\n"
"</html>\n"
;
