/* Auto-generated from src/matter_page.html - DO NOT EDIT MANUALLY */
#pragma once

static const char matter_html[] =
    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "<title>Sesame Matter</title>\n"
    "<style>\n"
    ":root {\n"
    "  --bg: #f8fafc;\n"
    "  --card: #ffffff;\n"
    "  --text: #0f172a;\n"
    "  --sub: #64748b;\n"
    "  --border: #e2e8f0;\n"
    "  --primary: #2563eb;\n"
    "  --primary-hover: #1d4ed8;\n"
    "  --green-bg: #dcfce7;\n"
    "  --green-fg: #166534;\n"
    "  --gray-bg: #f1f5f9;\n"
    "  --gray-fg: #475569;\n"
    "}\n"
    "@media (prefers-color-scheme: dark) {\n"
    "  :root {\n"
    "    --bg: #0f172a;\n"
    "    --card: #1e293b;\n"
    "    --text: #f8fafc;\n"
    "    --sub: #94a3b8;\n"
    "    --border: #334155;\n"
    "    --primary: #3b82f6;\n"
    "    --primary-hover: #2563eb;\n"
    "    --green-bg: #064e3b;\n"
    "    --green-fg: #6ee7b7;\n"
    "    --gray-bg: #334155;\n"
    "    --gray-fg: #cbd5e1;\n"
    "  }\n"
    "}\n"
    "* { box-sizing: border-box; margin: 0; padding: 0; }\n"
    "body {\n"
    "  font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, "
    "Helvetica, Arial, sans-serif;\n"
    "  background: var(--bg);\n"
    "  color: var(--text);\n"
    "  padding: 24px 16px;\n"
    "  display: flex;\n"
    "  justify-content: center;\n"
    "}\n"
    ".wrap {\n"
    "  width: 100%;\n"
    "  max-width: 440px;\n"
    "}\n"
    "header {\n"
    "  margin-bottom: 20px;\n"
    "  text-align: center;\n"
    "}\n"
    "h1 {\n"
    "  font-size: 1.35rem;\n"
    "  font-weight: 700;\n"
    "}\n"
    ".sub {\n"
    "  color: var(--sub);\n"
    "  font-size: 0.85rem;\n"
    "  margin-top: 2px;\n"
    "}\n"
    ".card {\n"
    "  background: var(--card);\n"
    "  border: 1px solid var(--border);\n"
    "  border-radius: 12px;\n"
    "  padding: 20px;\n"
    "  margin-bottom: 16px;\n"
    "  box-shadow: 0 1px 3px rgba(0,0,0,0.05);\n"
    "}\n"
    ".card-head {\n"
    "  display: flex;\n"
    "  align-items: center;\n"
    "  justify-content: space-between;\n"
    "  margin-bottom: 12px;\n"
    "}\n"
    ".card-head h2 {\n"
    "  font-size: 1.05rem;\n"
    "  font-weight: 600;\n"
    "}\n"
    ".badge {\n"
    "  font-size: 0.7rem;\n"
    "  font-weight: 600;\n"
    "  padding: 3px 8px;\n"
    "  border-radius: 9999px;\n"
    "  text-transform: uppercase;\n"
    "}\n"
    ".b-open {\n"
    "  background: var(--green-bg);\n"
    "  color: var(--green-fg);\n"
    "}\n"
    ".b-closed {\n"
    "  background: var(--gray-bg);\n"
    "  color: var(--gray-fg);\n"
    "}\n"
    "#qrcode {\n"
    "  display: block;\n"
    "  margin: 14px auto;\n"
    "  max-width: 100%;\n"
    "  width: 264px;\n"
    "  height: 264px;\n"
    "  border-radius: 6px;\n"
    "  box-shadow: 0 1px 4px rgba(0,0,0,0.12);\n"
    "}\n"
    ".code-box {\n"
    "  text-align: center;\n"
    "  margin: 14px 0 4px;\n"
    "}\n"
    ".code-lbl {\n"
    "  font-size: 0.75rem;\n"
    "  color: var(--sub);\n"
    "  text-transform: uppercase;\n"
    "  letter-spacing: 0.05em;\n"
    "}\n"
    ".code-val {\n"
    "  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "
    "monospace;\n"
    "  font-size: 1.45rem;\n"
    "  font-weight: 700;\n"
    "  letter-spacing: 0.12em;\n"
    "  margin: 4px 0;\n"
    "  user-select: all;\n"
    "}\n"
    ".code-raw {\n"
    "  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "
    "monospace;\n"
    "  font-size: 0.72rem;\n"
    "  color: var(--sub);\n"
    "  word-break: break-all;\n"
    "  user-select: all;\n"
    "  margin-top: 6px;\n"
    "}\n"
    ".fabric {\n"
    "  border: 1px solid var(--border);\n"
    "  border-radius: 8px;\n"
    "  padding: 10px 12px;\n"
    "  margin-bottom: 8px;\n"
    "}\n"
    ".fabric:last-child {\n"
    "  margin-bottom: 0;\n"
    "}\n"
    ".fab-top {\n"
    "  font-weight: 600;\n"
    "  font-size: 0.9rem;\n"
    "  display: flex;\n"
    "  justify-content: space-between;\n"
    "}\n"
    ".fab-row {\n"
    "  font-size: 0.8rem;\n"
    "  color: var(--sub);\n"
    "  font-family: ui-monospace, monospace;\n"
    "  margin-top: 2px;\n"
    "}\n"
    ".fab-row span {\n"
    "  color: var(--text);\n"
    "}\n"
    ".empty {\n"
    "  color: var(--sub);\n"
    "  font-size: 0.875rem;\n"
    "  line-height: 1.4;\n"
    "  text-align: center;\n"
    "  padding: 8px 0;\n"
    "}\n"
    ".btn {\n"
    "  display: inline-block;\n"
    "  width: 100%;\n"
    "  background: var(--primary);\n"
    "  color: #ffffff;\n"
    "  border: none;\n"
    "  border-radius: 6px;\n"
    "  padding: 9px 16px;\n"
    "  font-size: 0.875rem;\n"
    "  font-weight: 500;\n"
    "  cursor: pointer;\n"
    "  margin-top: 10px;\n"
    "  text-align: center;\n"
    "}\n"
    ".btn:hover {\n"
    "  background: var(--primary-hover);\n"
    "}\n"
    ".btn-sec {\n"
    "  background: transparent;\n"
    "  color: var(--text);\n"
    "  border: 1px solid var(--border);\n"
    "}\n"
    ".btn-sec:hover {\n"
    "  background: var(--border);\n"
    "}\n"
    ".btn-copy {\n"
    "  display: inline-block;\n"
    "  width: auto;\n"
    "  padding: 3px 12px;\n"
    "  font-size: 0.75rem;\n"
    "  margin-top: 4px;\n"
    "  border-radius: 4px;\n"
    "}\n"
    ".btn-row {\n"
    "  display: flex;\n"
    "  gap: 8px;\n"
    "  margin-top: 10px;\n"
    "}\n"
    ".btn-row .btn {\n"
    "  margin-top: 0;\n"
    "}\n"
    ".status-msg {\n"
    "  font-size: 0.8rem;\n"
    "  color: var(--sub);\n"
    "  text-align: center;\n"
    "  margin-top: 8px;\n"
    "}\n"
    ".hidden {\n"
    "  display: none !important;\n"
    "}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<div class=\"wrap\">\n"
    "  <header>\n"
    "    <h1>Sesame Matter</h1>\n"
    "    <p class=\"sub\">Garage Door Opener</p>\n"
    "    <div style=\"margin-top:6px;\"><a href=\"/logs.html\" "
    "style=\"font-size:0.8rem;color:var(--primary);text-decoration:none;\">"
    "Device Logs &rarr;</a></div>\n"
    "  </header>\n"
    "\n"
    "  <div id=\"setup-card\" class=\"card hidden\">\n"
    "    <div class=\"card-head\">\n"
    "      <h2>Commissioning</h2>\n"
    "      <span class=\"badge b-open\">Open</span>\n"
    "    </div>\n"
    "    <p class=\"sub\" style=\"text-align:center\">Scan with Apple Home, "
    "Google Home, or Home Assistant</p>\n"
    "    <canvas id=\"qrcode\"></canvas>\n"
    "    <div class=\"code-box\">\n"
    "      <div class=\"code-lbl\">Manual Pairing Code</div>\n"
    "      <div id=\"pair-code\" class=\"code-val\"></div>\n"
    "      <button class=\"btn btn-sec btn-copy\" "
    "onclick=\"copyPairCode(this)\">Copy Code</button>\n"
    "      <div id=\"qr-payload\" class=\"code-raw\"></div>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <div class=\"card\">\n"
    "    <div class=\"card-head\">\n"
    "      <h2>Commissioned Fabrics</h2>\n"
    "      <span id=\"fab-count\" class=\"badge b-closed\">0</span>\n"
    "    </div>\n"
    "    <div id=\"fabrics-list\"></div>\n"
    "    <div class=\"btn-row\">\n"
    "      <button id=\"btn-commission\" class=\"btn hidden\" "
    "onclick=\"openCommission()\">Open Commissioning</button>\n"
    "      <button class=\"btn btn-sec\" "
    "onclick=\"loadInfo()\">Refresh</button>\n"
    "    </div>\n"
    "    <div id=\"status-msg\" class=\"status-msg hidden\"></div>\n"
    "  </div>\n"
    "</div>\n"
    "\n"
    "<script>\n"
    "const t=[.2,3/8,5/9,2/3],o=(o,r)=>e=>{const "
    "n=4*o+e-4,f=\"*-04-39?2$%%$%%'$%''%'''%')(%'))%(++'(++'(+.'+-.',/3',33)-/"
    "5)-43).36)058*18<+37<+4:<,4:E,5<A-7>C/8@F/:EH/"
    "<EK0=FM1?IP2@KS3BNV4DPY5FS\\\\6HV_6IXb7K[e8N^i9Pam;Rdp<Tgt\".charCodeAt(n)"
    "-35,s=n>8?f:1,l=r/"
    "s|0,c=r%s,a=s-c,i=n>8?l*t[e]+(o>5)&-2:f,d=l-i;return{t:a*d+c*d+c,o:[[a,d],"
    "[c,d+1]],l:i}},r={L:0,M:1,Q:2,H:3},e=t=>new Uint8Array(t),n=t=>{const "
    "o=new Error(`lean-qr error ${t}`);throw "
    "o.code=t,o},f=(t,o=t*t,r=e(o))=>({size:t,i:r,get:(o,e)=>o>=0&&o<t&&!!(1&r["
    "e*t+o]),u(o,{on:r=[0,0,0],off:e=[0,0,0,0],pad:n=4,padX:f=n,padY:s=n}={}){"
    "const l=t+2*f,c=t+2*s,a=o.createImageData(l,c),i=new "
    "Uint32Array(a.data.buffer);a.data.set([...r,255]);const "
    "d=i[0];a.data.set([...e,255]);const u=i[0];for(let t=0;t<c;++t)for(let "
    "o=0;o<l;++o)i[t*l+o]=this.get(o-f,t-s)?d:u;return a},toCanvas(t,o){const "
    "r=t.getContext(\"2d\"),e=this.u(r,o);t.width=e.width,t.height=e.height,r."
    "putImageData(e,0,0)}}),s=[(t,o)=>1&(t^o),(t,o)=>1&o,t=>t%3,(t,o)=>(t+o)%3,"
    "(t,o)=>1&(t/"
    "3^o>>1),(t,o)=>(t&o&1)+t*o%3,(t,o)=>(t&o)+t*o%3&1,(t,o)=>(t^o)+t*o%3&1],l="
    "e(511);for(let t=0,o=1;t<255;o=2*o^285*(o>127))l[l[o+255]=t++]=o;const "
    "c=t=>l[t%255],a=t=>l[t+255],i=(t,o)=>{const "
    "r=e(t.length+o.length-1);for(let e=0;e<t.length;++e)for(let "
    "n=0;n<o.length;++n)r[e+n]^=c(t[e]+o[n]);return r.map(a)},d=(t,o)=>{const "
    "r=e(t.length+o.length-1);r.set(t,0);for(let "
    "e=0;e<t.length;++e)if(r[e]){const t=a(r[e]);for(let "
    "n=0;n<o.length;++n)r[e+n]^=c(o[n]+t)}return "
    "r.slice(t.length)},u=[[0],[0,0]];for(let "
    "t=1;t<30;++t)u.push(i(u[t],[0,t]));const _=(t,o)=>{const r=[[],[]];let "
    "n=0,f=0;for(const[e,s]of o.o)for(let l=0;l<e;++l,n+=s){const "
    "e=t.slice(n,n+s);r[0].push(e),r[1].push(d(e,u[o.l])),f+=s+o.l}const "
    "s=e(f);f=0;for(const t of r)for(let o=0,r=-1;r<f;++o){r=f;for(const r of "
    "t)o<r.length&&(s[f++]=r[o])}return s},p=(t,o,r)=>{let e=t<<=r;for(let "
    "t=134217728;t>>=1;)e&t&&(e^=o*(t>>r));return "
    "e|t},z=({size:t,i:o},r)=>{const e=(r,e,n,f)=>{for(;n-- "
    ">0;r+=t)o.fill(f,r,r+e)},n=(o,r,n)=>{for(let "
    "f=0;f++<3;n-=2)e(r*t+o-(n>>1)*(t+1),n,n,2|f)},f=2*((t-13)/(1+(r/7|0))/"
    "2+.75|0);if(r>1)for(let o=t-7;o>8;o-=f){for(let "
    "t=o;t>8;t-=f)n(o,t,5);o<t-7&&n(o,6,5)}if(r>6)for(let "
    "e=p(r,7973,12),n=1;n<7;++n)for(let r=12;r-- "
    ">9;e>>=1)o[n*t-r]=2|1&e;e(7,2,9,2),e(t-8,8,9,2);for(let "
    "r=0;r<t;++r)o[6*t+r]=3^1&r;n(3,3,7),n(t-4,3,7);for(let "
    "r=0;r<t;++r)for(let "
    "e=r;e<t;++e)o[e*t+r]=o[r*t+e];o[(t-8)*t+8]=3},g=({size:t,i:o})=>{const "
    "r=[];for(let "
    "e=t-2,n=t,f=-1;e>=0;e-=2){for(5===e&&(e=4);n+=f,-1!==n&&n!==t;){const "
    "f=n*t+e;o[f+1]||r.push(f+1),o[f]||r.push(f)}f*=-1}return "
    "r},w=({i:t},o,r)=>o.forEach((o,e)=>t[o]=r[e>>3]>>(7&~e)&1),y=({size:t,i:o}"
    ",r,e,n)=>{for(let e=0;e<t;++e)for(let n=0;n<t;++n){const "
    "f=e*t+n;o[f]^=!(r(n,e)||2&o[f])}let f=21522^p((1^n)<<3|e,1335,10);for(let "
    "r=0;r++<8;f>>=1)o[(r-(r<7))*t+8]=1&f,o[9*t-r]=1&f;for(let "
    "r=8;--r,f;f>>=1)o[8*t+r-(r<7)]=1&f,o[(t-r)*t+8]=1&f},E=({size:t,i:o},r=0,"
    "e=0)=>{for(let n=0;n<t;++n){for(let f=0;f<2;++f)for(let "
    "s,l=0,c=0,a=2;l<t;++l){const "
    "i=1&o[f?n*t+l:l*t+n];e+=i,c=(c>>1|2098176)&(3047517^i-1),2049&c&&(r+=40),"
    "i^a&&(s=0),a=i,r+=5===++s?3:s>5}if(n)for(let "
    "e=t+n,f=5*o[n-1]^o[n];e<t*t;e+=t){const "
    "t=5*o[e-1]^o[e];r+=3*!(1&(f|t)|4&(f^t)),f=t}}return "
    "r+10*(10*Math.abs(e/"
    "(t*t)-1)|0)},h=[],m=(t=n(1),{minCorrectionLevel:r=0,minVersion:l=1}={})=>{"
    "\"string\"!=typeof t&&n(5),t=(new TextEncoder).encode(t);const "
    "c=e(2957);c.set([113,164,t.length>>8]);for(let e=l;e<41;++e){let "
    "n=h[e];n||(h[e]=n=f(4*e+17),z(n,e),n.p=g(n));const "
    "l=o(e,n.p.length>>3)(r);if(l.t>=3+(e>9)+t.length){let "
    "o=e>9?3:2;for(c[o++]=t.length,c.set(t,o),o+=t.length-1;o<2954;c.set([236,"
    "17],o+=2));const a=f(n.size,n.i);return "
    "w(a,n.p,_(c,l)),s.map((t,o)=>{const e=f(a.size,a.i);return "
    "y(e,t,o,r),e.s=E(e),e}).sort((t,o)=>t.s-o.s)[0]}}n(4)};window.generateQR="
    "m;\n"
    "\n"
    "let rawPairCode = \"\";\n"
    "\n"
    "function drawQR(canvas, text) {\n"
    "  const qr = window.generateQR(text);\n"
    "  const pad = 4;\n"
    "  const scale = 8;\n"
    "  const size = (qr.size + pad * 2) * scale;\n"
    "  canvas.width = size;\n"
    "  canvas.height = size;\n"
    "  const ctx = canvas.getContext(\"2d\");\n"
    "  ctx.fillStyle = \"#ffffff\";\n"
    "  ctx.fillRect(0, 0, size, size);\n"
    "  ctx.fillStyle = \"#000000\";\n"
    "  for (let y = 0; y < qr.size; y++) {\n"
    "    for (let x = 0; x < qr.size; x++) {\n"
    "      if (qr.get(x, y)) {\n"
    "        ctx.fillRect((x + pad) * scale, (y + pad) * scale, scale, "
    "scale);\n"
    "      }\n"
    "    }\n"
    "  }\n"
    "}\n"
    "\n"
    "function fmtCode(c) {\n"
    "  if (c && c.length === 11) {\n"
    "    return c.slice(0, 4) + \"-\" + c.slice(4, 7) + \"-\" + c.slice(7);\n"
    "  }\n"
    "  return c || \"\";\n"
    "}\n"
    "\n"
    "function copyPairCode(btn) {\n"
    "  if (!rawPairCode) return;\n"
    "  const onDone = () => {\n"
    "    const orig = btn.textContent;\n"
    "    btn.textContent = \"Copied!\";\n"
    "    setTimeout(() => { btn.textContent = orig; }, 1500);\n"
    "  };\n"
    "  if (navigator.clipboard && navigator.clipboard.writeText) {\n"
    "    navigator.clipboard.writeText(rawPairCode).then(onDone).catch(() => "
    "fallbackCopy(rawPairCode, onDone));\n"
    "  } else {\n"
    "    fallbackCopy(rawPairCode, onDone);\n"
    "  }\n"
    "}\n"
    "\n"
    "function fallbackCopy(text, onDone) {\n"
    "  const ta = document.createElement(\"textarea\");\n"
    "  ta.value = text;\n"
    "  ta.style.position = \"fixed\";\n"
    "  ta.style.opacity = \"0\";\n"
    "  document.body.appendChild(ta);\n"
    "  ta.select();\n"
    "  try {\n"
    "    document.execCommand(\"copy\");\n"
    "    onDone();\n"
    "  } catch (e) {}\n"
    "  document.body.removeChild(ta);\n"
    "}\n"
    "\n"
    "async function loadInfo() {\n"
    "  const statusEl = document.getElementById(\"status-msg\");\n"
    "  try {\n"
    "    const res = await fetch(\"/matter/info\");\n"
    "    if (!res.ok) throw new Error(\"HTTP \" + res.status);\n"
    "    const data = await res.json();\n"
    "    render(data);\n"
    "    statusEl.classList.add(\"hidden\");\n"
    "  } catch (e) {\n"
    "    statusEl.textContent = \"Error: \" + e.message;\n"
    "    statusEl.classList.remove(\"hidden\");\n"
    "  }\n"
    "}\n"
    "\n"
    "function render(data) {\n"
    "  const setupCard = document.getElementById(\"setup-card\");\n"
    "  const btnComm = document.getElementById(\"btn-commission\");\n"
    "  const fabList = document.getElementById(\"fabrics-list\");\n"
    "  const fabCount = document.getElementById(\"fab-count\");\n"
    "\n"
    "  const fabrics = data.fabrics || [];\n"
    "  fabCount.textContent = fabrics.length;\n"
    "  fabCount.className = \"badge \" + (fabrics.length > 0 ? \"b-open\" : "
    "\"b-closed\");\n"
    "\n"
    "  if (data.setup && (data.setup.qr_code || "
    "data.setup.manual_pairing_code)) {\n"
    "    setupCard.classList.remove(\"hidden\");\n"
    "    if (data.setup.qr_code) {\n"
    "      drawQR(document.getElementById(\"qrcode\"), data.setup.qr_code);\n"
    "      document.getElementById(\"qr-payload\").textContent = "
    "data.setup.qr_code;\n"
    "    }\n"
    "    rawPairCode = data.setup.manual_pairing_code || \"\";\n"
    "    document.getElementById(\"pair-code\").textContent = "
    "fmtCode(rawPairCode);\n"
    "    btnComm.classList.add(\"hidden\");\n"
    "  } else {\n"
    "    setupCard.classList.add(\"hidden\");\n"
    "    btnComm.classList.remove(\"hidden\");\n"
    "  }\n"
    "\n"
    "  if (fabrics.length === 0) {\n"
    "    fabList.innerHTML = \"<p class=\\\"empty\\\">No fabrics commissioned "
    "yet.</p>\";\n"
    "  } else {\n"
    "    fabList.innerHTML = fabrics.map((f, i) => `\n"
    "      <div class=\"fabric\">\n"
    "        <div class=\"fab-top\">\n"
    "          <span>${f.label || \"Fabric #\" + (i + 1)}</span>\n"
    "          <span style=\"font-size:0.75rem;color:var(--sub)\">VID: "
    "${f.vendor_id}</span>\n"
    "        </div>\n"
    "        <div class=\"fab-row\">Fabric ID: "
    "<span>${f.fabric_id}</span></div>\n"
    "        <div class=\"fab-row\">Node ID: <span>${f.node_id}</span></div>\n"
    "      </div>\n"
    "    `).join(\"\");\n"
    "  }\n"
    "}\n"
    "\n"
    "async function openCommission() {\n"
    "  const statusEl = document.getElementById(\"status-msg\");\n"
    "  statusEl.textContent = \"Opening commissioning window...\";\n"
    "  statusEl.classList.remove(\"hidden\");\n"
    "  try {\n"
    "    const res = await fetch(\"/matter/commission\", { method: \"POST\" "
    "});\n"
    "    if (!res.ok) throw new Error(\"HTTP \" + res.status);\n"
    "    await loadInfo();\n"
    "  } catch (e) {\n"
    "    statusEl.textContent = \"Error: \" + e.message;\n"
    "  }\n"
    "}\n"
    "\n"
    "window.addEventListener(\"DOMContentLoaded\", loadInfo);\n"
    "</script>\n"
    "</body>\n"
    "</html>\n";
